### PR TITLE
fix the typo which causes mtls error "bad client cert type"

### PR DESCRIPTION
**Pull request by catbro666**
fix FTI-4678

### CODE REVIEW

**Review by Tieske — APPROVED** [review]
lgtm!

**Comment by catbro666** [comment]
Could we release a new version so that we can bump it on kong-ee?

**Comment by teb510** [comment]
@catbro666 or @Tieske what are the next steps here? thank you.

**Comment by Tieske** [comment]
@gszr I'm not familiar with this repo. Saw you pushed the last release. Can you help @catbro666 and @teb510 out here?

**Pull request merged**
